# Generated by Django 4.2.7 on 2024-05-23 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
