# Generated by Django 4.2.7 on 2024-05-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_team_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
