# Generated by Django 4.2.7 on 2024-05-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
