# Generated by Django 4.2.7 on 2024-05-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_day_blogpost_month_blogpost_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
