# Generated by Django 4.2.7 on 2024-05-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_company_remove_contact_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetUpdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=400)),
            ],
        ),
    ]
